# Development overrides for docker-compose.yml
# Этот файл автоматически применяется при запуске docker-compose up
version: '3.8'

services:
  bot-backend:
    build:
      target: development
    environment:
      - NODE_ENV=development
    volumes:
      # Volume mapping для hot reload
      - ./packages/backend:/app/packages/backend
      - ./packages/shared:/app/packages/shared
      # Исключаем node_modules из volume mapping
      - /app/node_modules
      - /app/packages/backend/node_modules
      - /app/packages/shared/node_modules
    command: ["npm", "--prefix", "packages/backend", "run", "dev"]
    # Увеличиваем timeout для development
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
