# Production configuration for docker-compose.yml
version: '3.8'

services:
  bot-backend:
    build:
      target: runtime
    environment:
      - NODE_ENV=production
    # В production не нужны volume mapping
    volumes: []
    command: ["node", "packages/backend/dist/index.js"]