services:
  - type: web
    name: app-backend
    runtime: docker
    plan: starter
    region: frankfurt
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      # добавь другие секреты по мере необходимости

  - type: web
    name: app-admin
    runtime: static
    plan: free
    buildCommand: npm ci && npm run -w packages/admin build && npm run -w packages/admin export
    staticPublishPath: packages/admin/admin-out
    # при необходимости можно добавить:
    # domains:
    #   - admin.example.com
