services:
  - type: web
    name: bot-test-front
    env: static
    buildCommand: npm ci && npm run build -w packages/admin
    staticPublishPath: packages/admin/admin-out
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NPM_VERSION
        value: 10
    routes:
      - type: rewrite
        source: /admin/*
        destination: /admin/index.html
