services:
  - type: web
    name: bot-test-front
    env: node
    buildCommand: npm ci && npm run build -w packages/operator-admin
    startCommand: npm run start -w packages/operator-admin
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NPM_VERSION
        value: 10
      - key: NEXT_PUBLIC_BASE_PATH
        value: /admin
      - key: PORT
        value: 10000
