services:
  - type: web
    name: bot-test-backend
    env: node
    buildCommand: npm ci --include=dev && npm run build -w packages/backend
    startCommand: npm run start -w packages/backend
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NPM_VERSION
        value: 10
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        value: https://bot-test-operator-admin.onrender.com
    # Переменные для backend (будут установлены в Render Dashboard)
    # DATABASE_URL
    # OPENAI_API_KEY
    # TELEGRAM_BOT_TOKEN
    # SUPABASE_URL
    # SUPABASE_KEY
    # SUPABASE_SERVICE_ROLE_KEY
