#!/usr/bin/env sh
cd -- "$(git rev-parse --show-toplevel)"

if ! command -v npx >/dev/null 2>&1; then
  echo "[husky] npx not found, skipping commitlint."
  exit 0
fi

if npx --no-install commitlint --edit "$1"; then
  echo "[husky] commitlint finished."
else
  echo "[husky] commitlint failed or not installed, but commit is allowed."
fi

exit 0
